# fly.toml app configuration file generated for bestagnos on 2023-06-29T15:47:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bestagnos"
primary_region = "cdg"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
